[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
counter_hook = "GwLhrTbEzTY91MphjQyA331P63yQDq31Frw5uvZ1umdQ"
token_2022_amm = "GYLAVXZXgZ22Bs9oGKnvTbc3AgxRFykABC5x6QzzLiYL"
token_setup = "Ba93wuicukbNB6djDoUkvMpDUxTw4Gzo3VH1oLfq9HBp"
amm = "H7dswT3BXcCEeVjjLWkfpBP2p5imuJy7Qaq9i5VCpoos"

[programs.localnet]
counter_hook = "GwLhrTbEzTY91MphjQyA331P63yQDq31Frw5uvZ1umdQ"
token_2022_amm = "GYLAVXZXgZ22Bs9oGKnvTbc3AgxRFykABC5x6QzzLiYL"
token_setup = "Ba93wuicukbNB6djDoUkvMpDUxTw4Gzo3VH1oLfq9HBp"
amm = "H7dswT3BXcCEeVjjLWkfpBP2p5imuJy7Qaq9i5VCpoos"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/wba-wallet.json"

[scripts]
deploy-0 = "yarn run ts-node deployment/00_generate_keypairs.ts"
deploy-1 = "yarn run ts-node deployment/create-amm.ts"
deploy-2 = "yarn run ts-node deployment/02_create-metadata.ts"
deploy-3 = "yarn run ts-node deployment/create-pool.ts"
emit = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/emit.ts"
gettime = "yarn run ts-node tests/000_gettime.ts"
swap = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/swap.ts"
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/*.ts"
test-0 = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/test.ts"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false

[test.validator]
bind_address = "0.0.0.0"
url = "https://api.devnet.solana.com"
ledger = ".anchor/test-ledger"
rpc_port = 8899
